### ISSUE TITLE
Many warning messages after install in my lumen project

### ISSUE THREAD

**Issue by stevehogo** [ssi-anik/testbench-lumen#4]
Hi @ssi-anik i have used your package in my lumen(10) project, after run composer require command, there are many warning messages appeared as below

`Warning: Ambiguous class resolution, "Database\Seeders\DatabaseSeeder" was found in both "/app/www/database/seeders/DatabaseSeeder.php" and "/app/www/vendor/laravel/lumen/database/seeders/DatabaseSeeder.php", the first will be used.
Warning: Ambiguous class resolution, "Database\Factories\UserFactory" was found in both "/app/www/database/factories/UserFactory.php" and "/app/www/vendor/laravel/lumen/database/factories/UserFactory.php", the first will be used.
Warning: Ambiguous class resolution, "App\Events\ExampleEvent" was found in both "/app/www/app/Events/ExampleEvent.php" and "/app/www/vendor/laravel/lumen/app/Events/ExampleEvent.php", the first will be used.
Warning: Ambiguous class resolution, "App\Events\Event" was found in both "/app/www/app/Events/Event.php" and "/app/www/vendor/laravel/lumen/app/Events/Event.php", the first will be used.
Warning: Ambiguous class resolution, "App\Exceptions\Handler" was found in both "/app/www/app/Exceptions/Handler.php" and "/app/www/vendor/laravel/lumen/app/Exceptions/Handler.php", the first will be used.
Warning: Ambiguous class resolution, "App\Jobs\Job" was found in both "/app/www/app/Jobs/Job.php" and "/app/www/vendor/laravel/lumen/app/Jobs/Job.php", the first will be used.
Warning: Ambiguous class resolution, "App\Jobs\ExampleJob" was found in both "/app/www/app/Jobs/ExampleJob.php" and "/app/www/vendor/laravel/lumen/app/Jobs/ExampleJob.php", the first will be used.
Warning: Ambiguous class resolution, "App\Listeners\ExampleListener" was found in both "/app/www/app/Listeners/ExampleListener.php" and "/app/www/vendor/laravel/lumen/app/Listeners/ExampleListener.php", the first will be used.
Warning: Ambiguous class resolution, "App\Console\Kernel" was found in both "/app/www/app/Console/Kernel.php" and "/app/www/vendor/laravel/lumen/app/Console/Kernel.php", the first will be used.
Warning: Ambiguous class resolution, "App\Http\Controllers\Controller" was found in both "/app/www/app/Http/Controllers/Controller.php" and "/app/www/vendor/laravel/lumen/app/Http/Controllers/Controller.php", the first will be used.
Warning: Ambiguous class resolution, "App\Http\Controllers\ExampleController" was found in both "/app/www/app/Http/Controllers/ExampleController.php" and "/app/www/vendor/laravel/lumen/app/Http/Controllers/ExampleController.php", the first will be used.
Warning: Ambiguous class resolution, "App\Http\Middleware\ExampleMiddleware" was found in both "/app/www/app/Http/Middleware/ExampleMiddleware.php" and "/app/www/vendor/laravel/lumen/app/Http/Middleware/ExampleMiddleware.php", the first will be used.
Warning: Ambiguous class resolution, "App\Http\Middleware\Authenticate" was found in both "/app/www/app/Http/Middleware/Authenticate.php" and "/app/www/vendor/laravel/lumen/app/Http/Middleware/Authenticate.php", the first will be used.
Warning: Ambiguous class resolution, "App\Providers\AuthServiceProvider" was found in both "/app/www/app/Providers/AuthServiceProvider.php" and "/app/www/vendor/laravel/lumen/app/Providers/AuthServiceProvider.php", the first will be used.
Warning: Ambiguous class resolution, "App\Providers\EventServiceProvider" was found in both "/app/www/app/Providers/EventServiceProvider.php" and "/app/www/vendor/laravel/lumen/app/Providers/EventServiceProvider.php", the first will be used.
Warning: Ambiguous class resolution, "App\Providers\AppServiceProvider" was found in both "/app/www/app/Providers/AppServiceProvider.php" and "/app/www/vendor/laravel/lumen/app/Providers/AppServiceProvider.php", the first will be used.
Warning: Ambiguous class resolution, "App\Models\User" was found in both "/app/www/app/Models/User.php" and "/app/www/vendor/laravel/lumen/app/Models/User.php", the first will be used.`

I think you should remove out this line `"laravel/lumen": "^6.0|^7.0|^8.0|^9.0|^10.0",` from composer.json

Regards,
Steve

**Comment by ssi-anik** [comment]
Hello @stevehogo

This package is intended to be used with the package and not in the Lumen project.

Are you using it in the project?

**Comment by stevehogo** [comment]
@ssi-anik yes, i used in the Lumen project.

**Comment by ssi-anik** [comment]
Then you're not doing it correctly. May I ask the reason to add this package in your lumen project?
